In [35]:
import pandas as pd
from sqlalchemy import create_engine
import sqlalchemy
from datetime import datetime

In [36]:
# Leer los archivos .csv
df_challenges = pd.read_csv("challenges - challenges.csv")
df_profiles = pd.read_csv("profiles - Hoja 1.csv")
df_resumes = pd.read_csv("resumes - resumes.csv")
df_users = pd.read_csv("users - users.csv")

In [42]:
df_challenges

,id,name,description,status,opencall_objective,created_at
0,450,Cantantes de Reguetonland que buscan patrocinios,\nBuscamos jóvenes comprometidos con la justic...,published,Artistas,2024-07-05
1,460,Conviértete en el próximo líder del cambio soc...,¿Te gustaría convertirte en un compositor de c...,published,Artistas,2024-07-06
2,470,Te gustaría convertirte en un compositor,Formación personalizada y la oportunidad de ap...,published,Artistas,2024-07-07
3,480,Sé el mejor presentador de televisión,¡Domina el arte del casting con una mentoría e...,open,Artistas,2024-07-08
4,490,Domina el arte del casting con una mentoría,¿Sueñas con convertirte en empresario con el r...,open,Innovador,2024-07-09
5,500,Sueñas con convertirte en empresario,La oportunidad de competir en el Campeonato Mu...,published,Artistas,2024-07-10
6,510,Eres un apasionado del tango con sueños de bri...,\nBuscamos Jugadores y jugadoras apasionados p...,closed,Deportistas,2024-07-11
7,520,Demuestra tu talento y únete al desafío de fútbol,"Buscamos Emprendedores, startups y desarrollad...",published,Innovador,2024-02-10
8,530,La oportunidad de presentar tu proyecto,"Buscamos Emprendedores, startups y desarrollad...",published,Innovador,2024-02-11
9,540,¡Desafío de Diseño para una Marca de Moda de L...,Buscamos diseñadores talentosos y creativos qu...,published,Artistas,2024-02-12
10,550,¡Desafío de Optimización para Tiendas en Línea!,Estamos buscando soluciones innovadoras para m...,published,Innovador,2024-09-20
11,560,Buscamos talento musical para viralizar su tal...,Esta es tu oportunidad. Buscamos a músicos que...,published,Artistas,2024-09-21

In [38]:
# Cambiar el tipo de dato, fecha
df_challenges['created_at'] = pd.to_datetime(df_challenges['created_at'])
df_profiles['updated_at'] = pd.to_datetime(df_profiles['updated_at'])
df_profiles['created_at'] = pd.to_datetime(df_profiles['created_at'])
df_resumes['created_at'] = pd.to_datetime(df_resumes['created_at'])
df_users['created_at'] = pd.to_datetime(df_users['created_at'])
df_users['updated_at'] = pd.to_datetime(df_users['updated_at'])

In [39]:
# Cambiar la estructura de la fecha
df_challenges['created_at'] = df_challenges['created_at'].dt.strftime('%Y-%m-%d')
df_profiles['updated_at'] = df_profiles['updated_at'].dt.strftime('%Y-%m-%d')
df_profiles['created_at'] = df_profiles['created_at'].dt.strftime('%Y-%m-%d')
df_resumes['created_at'] = df_resumes['created_at'].dt.strftime('%Y-%m-%d')
df_users['created_at'] = df_users['created_at'].dt.strftime('%Y-%m-%d')
df_users['updated_at'] = df_users['updated_at'].dt.strftime('%Y-%m-%d')

In [40]:
# Conexión a MySQL
user = 'root'       # Reemplaza con tu usuario
password = 'Camilo12*'   # Reemplaza con tu contraseña
host = 'localhost'           # Por ejemplo, 'localhost' o la IP de tu servidor MySQL
database = 'talentpitch'   # El nombre de tu base de datos

# Crear la conexión
engine = create_engine(f'mysql+mysqlconnector://{user}:{password}@{host}/{database}')

# Cargar los DataFrames en MySQL
df_challenges.to_sql('challenges', con=engine, if_exists='replace', index=False)
df_profiles.to_sql('profiles', con=engine, if_exists='replace', index=False)
df_resumes.to_sql('resumes', con=engine, if_exists='replace', index=False)
df_users.to_sql('users', con=engine, if_exists='replace', index=False)

print("Datos cargados en MySQL con éxito.")

Datos cargados en MySQL con éxito.